### ISSUE TITLE
Allow setting a global default `data-reveal-hidden-class`

### ISSUE THREAD

**Issue by ThomasLandauer** [stimulus-components/stimulus-reveal-controller#10]
When using the reveal controller in numerous places, it's cumbersome to repeat `data-reveal-hidden-class="xy"` over and over again. Would it be possible to allow setting this globally, e.g. when registering the controller in `stimulus_bootstrap.js`:
```js
app.register('reveal', Reveal, {'reveal-hidden-class': 'xy'});
```

**Comment by guillaumebriday** [comment]
I'm not sure you can pass options like this in the register function, there is no mention about it here: https://stimulus.hotwired.dev/handbook/installing

But you can extends the controller to have the same behavior: https://www.stimulus-components.com/docs/stimulus-reveal-controller/
