### ISSUE TITLE
Uncaught TypeError: class heritage undefined is not an object or null

### ISSUE THREAD

**Issue by wnm** [stimulus-components/stimulus-reveal-controller#12]
We are on Rails 7 with webpacker 5.4.4 and when I install the component with

`$ yarn add stimulus-reveal-controller`

and

```
import { Application } from '@hotwired/stimulus'
import Reveal from 'stimulus-reveal-controller'

const application = Application.start()
application.register('reveal', Reveal)
```

I get a `Uncaught TypeError: class heritage undefined is not an object or null` error.

Am I doing something wrong?

**Comment by guillaumebriday** [comment]
I think it has been fixed
