### ISSUE TITLE
Suggestion: Support Action Parameters to allow targeting specific items

### ISSUE THREAD

**Issue by ThomasLandauer** [stimulus-components/stimulus-reveal-controller#14]
With a setup like this, you cannot use `reveal`, right?:
```html
<button>Toggle Foo</button>
<button>Toggle Bar</button>
<div>Foo</div>
<div>Bar</div>
```
...Since you'd have to wrap it in one controller, and then each button would toggle both `<div>`s.

What about adding an [Action Parameter](https://stimulus.hotwired.dev/reference/actions#action-parameters) that passes a CSS selector, like this?:
```html
<button data-action="reveal#toggle" data-reveal-item-param="#foo">Toggle Foo</button>
<button data-action="reveal#toggle" data-reveal-item-param="#bar">Toggle Bar</button>
<div id="foo">Foo</div>
<div id="bar">Bar</div>
```

**Comment by guillaumebriday** [comment]
If it's still an issue, please reopen it in the main repo: https://github.com/stimulus-components/stimulus-components
