### ISSUE TITLE
Support aria-expanded

### ISSUE THREAD

**Issue by tmaier** [stimulus-components/stimulus-reveal-controller#5]
I wonder how to enable proper accessibility/ARIA support for a navigation menu, which gets revealed with stimulus-reveal-controller.

This is an implementation reference: https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html
The challenge is `aria-expanded="true"` and `aria-expanded="false"` respectively, when the menu has been revealed or not.

Is there currently already a way to get this working?

**Comment by guillaumebriday** [comment]
That would be nice! 

Could you open a PR please 🙏

**Comment by guillaumebriday** [comment]
Hi @tmaier

Can you review this PR please https://github.com/stimulus-components/stimulus-reveal-controller/pull/11?

**Comment by tmaier** [comment]
Hi @guillaumebriday, I will try to do a test run within the next couple of days.
