### ISSUE TITLE
Close when pressing escape

### ISSUE THREAD

**Issue by tmaier** [stimulus-components/stimulus-reveal-controller#6]
It would be great, if this controller would allow to close when the escape key is being pressed.

<details>
<summary>How are others solving this?</summary>

https://www.npmjs.com/package/stimulus-reveal has a `data-reveal-hide-keys-value` attribute
</details>

**Comment by guillaumebriday** [comment]
I think you can achieve this with a classic event listener on document or window.

See https://stimulus.hotwired.dev/reference/actions#global-events
