### ISSUE TITLE
Close when clicking away

### ISSUE THREAD

**Issue by tmaier** [stimulus-components/stimulus-reveal-controller#7]
It would be great, if this controller would allow to close when the use clicks away.

<details>
<summary>How are others solving this?</summary>

https://www.npmjs.com/package/stimulus-reveal has a `data-reveal-away-value` attribute
</details>

**Comment by guillaumebriday** [comment]
I think you can achieve this with a classic event listener on document or window.

See https://stimulus.hotwired.dev/reference/actions#global-events
