### ISSUE TITLE
Export TS types

### ISSUE THREAD

**Issue by janklimo** [stimulus-components/stimulus-reveal-controller#8]
This would be a quick win since the package is written in TS.

Something like this could do the trick:

```json
{
  "scripts": {
    "build": "tsup ./src/index.ts --format esm,cjs --dts --minify",
  }
}
```

or there seems to be a [vite plugin](https://github.com/qmhc/vite-plugin-dts).

**Comment by guillaumebriday** [comment]
Hi @janklimo 

Great idea!

Can you open a PR with tsup and the package.json updated?

Thank!
