### ISSUE TITLE
why not -value?

### ISSUE THREAD

**Issue by tacman** [stimulus-components/stimulus-reveal-controller#9]
In the documentation on https://www.stimulus-components.com/docs/stimulus-reveal-controller/, the example has

<div data-controller="reveal" data-reveal-hidden-class="d-none">

But I thought that stimulus controllers had -value at the end, e.g.

<div data-controller="reveal" data-reveal-hidden-class-value="d-none">

I'm using the stimulus twig function in Symfony to generate the HTML, and it creates the data- property with the -value suffix.

**Comment by guillaumebriday** [comment]
Hey!

I'm not sure what you mean since there is not suffix `-value`

Feel free to reopen the issue if needed
